services:
  desafio-database:
    container_name: desafio-database
    image: mysql:5.7
    restart: unless-stopped
    command: --innodb-use-native-aio=0 
    tty: true
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: desafio-full-cycle
      MYSQL_PASSWORD: root
    ports:
      - '3300:3306'
    networks:
      - desafio-network

  desafio-app:
    container_name: desafio-app
    build:
      context: .
      dockerfile: node/Dockerfile.dev
    restart: unless-stopped
    tty: true
    volumes:
      - ./node:/app
    command: sh -c "dockerize -wait tcp://desafio-database:3306 -timeout 20s && node /app/index.js"
    ports:
      - '3000:3000'
    depends_on:
      - desafio-database
    networks:
      - desafio-network

  desafio-proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:8080'
    networks:
      - desafio-network
    depends_on:
      - desafio-app

networks:
  desafio-network:
    driver: bridge