CREATE DATABASE IF NOT EXISTS `desafio-full-cycle`;
USE `desafio-full-cycle`;

CREATE TABLE IF NOT EXISTS `people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,

  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;